apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sandbox-com-tls
  namespace: sandbox
spec:
  secretName: sandbox-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sandbox.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - sandbox.example.com


